apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "83eba9a206dcbecc1374f1e12ba0c3ee6d332a71"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:83eba9a206dcbecc1374f1e12ba0c3ee6d332a71'
          ports:
            - containerPort: 80
