apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "9477dec69d966fc6d033694041991c210d8e1909"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:9477dec69d966fc6d033694041991c210d8e1909'
          ports:
            - containerPort: 80
